/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZustandIndexImport } from './routes/zustand/index'
import { Route as TsqueryIndexImport } from './routes/tsquery/index'
import { Route as ReduxIndexImport } from './routes/redux/index'
import { Route as ZustandAddImport } from './routes/zustand/add'
import { Route as ZustandListingIdImport } from './routes/zustand/$listingId'
import { Route as TsqueryAddImport } from './routes/tsquery/add'
import { Route as TsqueryListingIdImport } from './routes/tsquery/$listingId'
import { Route as ReduxAddImport } from './routes/redux/add'
import { Route as ReduxListingIdImport } from './routes/redux/$listingId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ZustandIndexRoute = ZustandIndexImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRoute,
} as any)

const TsqueryIndexRoute = TsqueryIndexImport.update({
  id: '/tsquery/',
  path: '/tsquery/',
  getParentRoute: () => rootRoute,
} as any)

const ReduxIndexRoute = ReduxIndexImport.update({
  id: '/redux/',
  path: '/redux/',
  getParentRoute: () => rootRoute,
} as any)

const ZustandAddRoute = ZustandAddImport.update({
  id: '/zustand/add',
  path: '/zustand/add',
  getParentRoute: () => rootRoute,
} as any)

const ZustandListingIdRoute = ZustandListingIdImport.update({
  id: '/zustand/$listingId',
  path: '/zustand/$listingId',
  getParentRoute: () => rootRoute,
} as any)

const TsqueryAddRoute = TsqueryAddImport.update({
  id: '/tsquery/add',
  path: '/tsquery/add',
  getParentRoute: () => rootRoute,
} as any)

const TsqueryListingIdRoute = TsqueryListingIdImport.update({
  id: '/tsquery/$listingId',
  path: '/tsquery/$listingId',
  getParentRoute: () => rootRoute,
} as any)

const ReduxAddRoute = ReduxAddImport.update({
  id: '/redux/add',
  path: '/redux/add',
  getParentRoute: () => rootRoute,
} as any)

const ReduxListingIdRoute = ReduxListingIdImport.update({
  id: '/redux/$listingId',
  path: '/redux/$listingId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/redux/$listingId': {
      id: '/redux/$listingId'
      path: '/redux/$listingId'
      fullPath: '/redux/$listingId'
      preLoaderRoute: typeof ReduxListingIdImport
      parentRoute: typeof rootRoute
    }
    '/redux/add': {
      id: '/redux/add'
      path: '/redux/add'
      fullPath: '/redux/add'
      preLoaderRoute: typeof ReduxAddImport
      parentRoute: typeof rootRoute
    }
    '/tsquery/$listingId': {
      id: '/tsquery/$listingId'
      path: '/tsquery/$listingId'
      fullPath: '/tsquery/$listingId'
      preLoaderRoute: typeof TsqueryListingIdImport
      parentRoute: typeof rootRoute
    }
    '/tsquery/add': {
      id: '/tsquery/add'
      path: '/tsquery/add'
      fullPath: '/tsquery/add'
      preLoaderRoute: typeof TsqueryAddImport
      parentRoute: typeof rootRoute
    }
    '/zustand/$listingId': {
      id: '/zustand/$listingId'
      path: '/zustand/$listingId'
      fullPath: '/zustand/$listingId'
      preLoaderRoute: typeof ZustandListingIdImport
      parentRoute: typeof rootRoute
    }
    '/zustand/add': {
      id: '/zustand/add'
      path: '/zustand/add'
      fullPath: '/zustand/add'
      preLoaderRoute: typeof ZustandAddImport
      parentRoute: typeof rootRoute
    }
    '/redux/': {
      id: '/redux/'
      path: '/redux'
      fullPath: '/redux'
      preLoaderRoute: typeof ReduxIndexImport
      parentRoute: typeof rootRoute
    }
    '/tsquery/': {
      id: '/tsquery/'
      path: '/tsquery'
      fullPath: '/tsquery'
      preLoaderRoute: typeof TsqueryIndexImport
      parentRoute: typeof rootRoute
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand'
      preLoaderRoute: typeof ZustandIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/redux/$listingId': typeof ReduxListingIdRoute
  '/redux/add': typeof ReduxAddRoute
  '/tsquery/$listingId': typeof TsqueryListingIdRoute
  '/tsquery/add': typeof TsqueryAddRoute
  '/zustand/$listingId': typeof ZustandListingIdRoute
  '/zustand/add': typeof ZustandAddRoute
  '/redux': typeof ReduxIndexRoute
  '/tsquery': typeof TsqueryIndexRoute
  '/zustand': typeof ZustandIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/redux/$listingId': typeof ReduxListingIdRoute
  '/redux/add': typeof ReduxAddRoute
  '/tsquery/$listingId': typeof TsqueryListingIdRoute
  '/tsquery/add': typeof TsqueryAddRoute
  '/zustand/$listingId': typeof ZustandListingIdRoute
  '/zustand/add': typeof ZustandAddRoute
  '/redux': typeof ReduxIndexRoute
  '/tsquery': typeof TsqueryIndexRoute
  '/zustand': typeof ZustandIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/redux/$listingId': typeof ReduxListingIdRoute
  '/redux/add': typeof ReduxAddRoute
  '/tsquery/$listingId': typeof TsqueryListingIdRoute
  '/tsquery/add': typeof TsqueryAddRoute
  '/zustand/$listingId': typeof ZustandListingIdRoute
  '/zustand/add': typeof ZustandAddRoute
  '/redux/': typeof ReduxIndexRoute
  '/tsquery/': typeof TsqueryIndexRoute
  '/zustand/': typeof ZustandIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redux/$listingId'
    | '/redux/add'
    | '/tsquery/$listingId'
    | '/tsquery/add'
    | '/zustand/$listingId'
    | '/zustand/add'
    | '/redux'
    | '/tsquery'
    | '/zustand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redux/$listingId'
    | '/redux/add'
    | '/tsquery/$listingId'
    | '/tsquery/add'
    | '/zustand/$listingId'
    | '/zustand/add'
    | '/redux'
    | '/tsquery'
    | '/zustand'
  id:
    | '__root__'
    | '/'
    | '/redux/$listingId'
    | '/redux/add'
    | '/tsquery/$listingId'
    | '/tsquery/add'
    | '/zustand/$listingId'
    | '/zustand/add'
    | '/redux/'
    | '/tsquery/'
    | '/zustand/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ReduxListingIdRoute: typeof ReduxListingIdRoute
  ReduxAddRoute: typeof ReduxAddRoute
  TsqueryListingIdRoute: typeof TsqueryListingIdRoute
  TsqueryAddRoute: typeof TsqueryAddRoute
  ZustandListingIdRoute: typeof ZustandListingIdRoute
  ZustandAddRoute: typeof ZustandAddRoute
  ReduxIndexRoute: typeof ReduxIndexRoute
  TsqueryIndexRoute: typeof TsqueryIndexRoute
  ZustandIndexRoute: typeof ZustandIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ReduxListingIdRoute: ReduxListingIdRoute,
  ReduxAddRoute: ReduxAddRoute,
  TsqueryListingIdRoute: TsqueryListingIdRoute,
  TsqueryAddRoute: TsqueryAddRoute,
  ZustandListingIdRoute: ZustandListingIdRoute,
  ZustandAddRoute: ZustandAddRoute,
  ReduxIndexRoute: ReduxIndexRoute,
  TsqueryIndexRoute: TsqueryIndexRoute,
  ZustandIndexRoute: ZustandIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/redux/$listingId",
        "/redux/add",
        "/tsquery/$listingId",
        "/tsquery/add",
        "/zustand/$listingId",
        "/zustand/add",
        "/redux/",
        "/tsquery/",
        "/zustand/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/redux/$listingId": {
      "filePath": "redux/$listingId.tsx"
    },
    "/redux/add": {
      "filePath": "redux/add.tsx"
    },
    "/tsquery/$listingId": {
      "filePath": "tsquery/$listingId.tsx"
    },
    "/tsquery/add": {
      "filePath": "tsquery/add.tsx"
    },
    "/zustand/$listingId": {
      "filePath": "zustand/$listingId.tsx"
    },
    "/zustand/add": {
      "filePath": "zustand/add.tsx"
    },
    "/redux/": {
      "filePath": "redux/index.tsx"
    },
    "/tsquery/": {
      "filePath": "tsquery/index.tsx"
    },
    "/zustand/": {
      "filePath": "zustand/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
