services:
  client:
    build:
      context: ./client
    ports:
      - "4002:4002"
      - "9222:9222"
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: "npm run dev"
  server:
    build:
      context: ./server
    ports:
      - "5002:5002"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: postgres
      PGDATABASE: statemanagement
      PGPORT: 5432
      PORT: 5002
      HOST: localhost
      API_URL: http://localhost:5002
    command: "npm run dev"
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statemanagement
volumes:
  db-volume:
