services:
  client-debug:
    build:
      context: ./client
    ports:
      - "4002:4002"
      - "9222:9222"
    depends_on:
      - server-debug
    volumes:
      - ./client:/app/
      - /app/node_modules
    environment:
       NODE_ENV: development
    command: "npm run dev"
  server-debug:
    build:
      context: ./server
    ports:
      - "5002:5002"
      - "9229:9229"
    depends_on:
      - db-debug
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
       NODE_ENV: development
    command: "npm run dev"
  db-debug:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-volume:
