INSERT INTO categories (id, category_name, parent_id, active)
VALUES (1, 'Antiques & collectables', 0, true),
	(2, 'Baby gear', 0, false),
	(3, 'Books', 0, false),
	(4, 'Building & renovation', 0, false),
	(5, 'Business, farming & industry', 0, false),
	(6, 'Clothing, Fashion', 0, false),
	(7, 'Computers & Electronics', 0, true),
	(8, 'Gaming', 0, false),
	(9, 'Health, beauty', 0, false),
	(10, 'Home, living', 0, false),
	(11, 'Jewellery, watches', 0, false),
	(12, 'Mobile phones', 0, false),
	(13, 'Music, instruments', 0, false),
	(14, 'Pets, animals', 0, false),
	(15, 'Sports', 0, false),
	(16, 'Toys, models', 0, false),
	(17, 'Advertising', 1, true),
	(18, 'Alcohol related', 1, true),
	(19, 'Appliances', 1, true),
	(20, 'Art deco & retro', 1, true),
	(21, 'Automotive & transport', 1, true),
	(22, 'Banknotes', 1, true),
	(23, 'Bottles', 1, true),
	(24, 'Clocks & scientific instruments', 1, true),
	(25, 'Coins', 1, true),
	(26, 'Cultural & ethnic', 1, true),
	(27, 'Documents & maps', 1, true),
	(28, 'Flags', 1, true),
	(29, 'Food & drink', 1, true),
	(30, 'Furniture & woodenware', 1, true),
	(31, 'Jewellery', 1, true),
	(32, 'Military', 1, true),
	(33, 'Movie & TV memorabilia', 1, true),
	(34, 'Museum pieces & artifacts', 1, true),
	(35, 'New Zealand & Maori', 1, true),
	(36, 'Ornaments & figurines', 1, true),
	(37, 'Phonecards', 1, true),
	(38, 'Pins, badges & patches', 1, true),
	(39, 'Postcards & writing', 1, true),
	(40, '3D Printers & Supplies', 7, true),
	(41, 'Blank discs & cases', 7, true),
	(42, 'Cables & adaptors', 7, true),
	(43, 'Components', 7, true),
	(44, 'Computer furniture', 7, true),
	(45, 'Desktops', 7, true),
	(46, 'Domain names', 7, true),
	(47, 'External storage', 7, true),
	(48, 'Laptops', 7, true),
	(49, 'Monitors', 7, true),
	(50, 'Networking & modems', 7, true),
	(51, 'Peripherals', 7, true),
	(52, 'Printer accessories & supplies', 7, true),
	(53, 'Printers', 7, true),
	(54, 'Servers', 7, true),
	(55, 'Software', 7, true),
	(56, 'Tablets & E-book readers', 7, true),
	(57, 'Vintage', 7, true),
	(58, 'Other', 7, true);